# -*- conf -*-

[main]
term = xterm-256color
font = Iosevka Extended:size=14

[scrollback]
lines = 1000

# Colors Srcery
[colors-dark]
foreground=ffffff
background=0e0e0e

regular0=0e0e0e
regular1=ef2f27
regular2=2ab028
regular3=fbb829
regular4=2c78bf
regular5=e02c6d
regular6=0aaeb3
regular7=c4c4c4

bright0=919191
bright1=f75341
bright2=8bca37
bright3=fed06e
bright4=68a8e4
bright5=ff5c8f
bright6=2be4d0
bright7=ffffff
